/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg3dsecure.Client;

import CertFile.CertFile;
import pkg3dsecure.ACS.authServer.ReponseAuth;
import pkg3dsecure.ACS.authServer.RequeteAuth;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.net.ssl.SSLSocket;
import javax.net.ssl.SSLSocketFactory;

/**
 *
 * @author Aurélien Bolkaerts
 */
public class ClientFrame extends javax.swing.JFrame {

    private ObjectInputStream ois;
    private ObjectOutputStream oos;
    private Socket cliSock;
    
   public ClientFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        RequestPanel = new javax.swing.JPanel();
        NomLabel = new javax.swing.JLabel();
        NomTF = new javax.swing.JTextField();
        PINLabel = new javax.swing.JLabel();
        PINTF = new javax.swing.JPasswordField();
        EmptyPanel = new javax.swing.JPanel();
        AuthButton = new javax.swing.JButton();
        AnswerPanel = new javax.swing.JPanel();
        NomBanqueLabel = new javax.swing.JLabel();
        NomBanqueTF = new javax.swing.JTextField();
        NomClientLabel = new javax.swing.JLabel();
        NomClientTF = new javax.swing.JTextField();
        NumSerieLabel = new javax.swing.JLabel();
        NumSerieTF = new javax.swing.JTextField();
        DebugScrollPanel = new javax.swing.JScrollPane();
        DebugTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        RequestPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        RequestPanel.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        NomLabel.setText("Nom");
        NomLabel.setMaximumSize(new java.awt.Dimension(150, 16));
        NomLabel.setMinimumSize(new java.awt.Dimension(150, 16));
        NomLabel.setPreferredSize(new java.awt.Dimension(150, 16));
        RequestPanel.add(NomLabel);
        RequestPanel.add(NomTF);

        PINLabel.setText("PIN");
        RequestPanel.add(PINLabel);
        RequestPanel.add(PINTF);

        javax.swing.GroupLayout EmptyPanelLayout = new javax.swing.GroupLayout(EmptyPanel);
        EmptyPanel.setLayout(EmptyPanelLayout);
        EmptyPanelLayout.setHorizontalGroup(
            EmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        EmptyPanelLayout.setVerticalGroup(
            EmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        RequestPanel.add(EmptyPanel);

        AuthButton.setText("Authentification");
        AuthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthButtonActionPerformed(evt);
            }
        });
        RequestPanel.add(AuthButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(RequestPanel, gridBagConstraints);

        AnswerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AnswerPanel.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        NomBanqueLabel.setText("Nom de la banque");
        NomBanqueLabel.setMaximumSize(new java.awt.Dimension(150, 16));
        NomBanqueLabel.setMinimumSize(new java.awt.Dimension(150, 16));
        NomBanqueLabel.setPreferredSize(new java.awt.Dimension(150, 16));
        AnswerPanel.add(NomBanqueLabel);

        NomBanqueTF.setEditable(false);
        AnswerPanel.add(NomBanqueTF);

        NomClientLabel.setText("Nom du client");
        AnswerPanel.add(NomClientLabel);

        NomClientTF.setEditable(false);
        AnswerPanel.add(NomClientTF);

        NumSerieLabel.setText("Numéro de série");
        AnswerPanel.add(NumSerieLabel);

        NumSerieTF.setEditable(false);
        AnswerPanel.add(NumSerieTF);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(AnswerPanel, gridBagConstraints);

        DebugScrollPanel.setPreferredSize(new java.awt.Dimension(300, 275));

        DebugTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Info"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DebugTable.setMaximumSize(new java.awt.Dimension(100, 0));
        DebugTable.setPreferredSize(new java.awt.Dimension(100, 0));
        DebugScrollPanel.setViewportView(DebugTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(DebugScrollPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AuthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthButtonActionPerformed
        try {
            //Connexion au serveur sur le port non SSL
            System.out.println("Connexion au serveur sur le port non-SSL");
            String adresse = "localhost";
            
            int port = 2500;
            
            cliSock = new Socket(adresse,port);
            ois = new ObjectInputStream(cliSock.getInputStream());
            oos = new ObjectOutputStream(cliSock.getOutputStream());
            
            //Réception du premier packet indiquant le port SSL éventuel
            System.out.println("Réception du premier packet indiquant le port SSL éventuel");
            String isSsl = ois.readUTF();
            System.out.println("SSL - " + isSsl);
            if(!isSsl.equals("no-SSL")){
                int portSSL = Integer.parseInt(isSsl.substring(isSsl.lastIndexOf("#")+1));
                SSLSocketFactory SslSFac = CertFile.getSSLClientSocketFactory("C:/Users/Aurélien Bolkaerts/Desktop/key/acs_keystore.jks","password","password");
                SSLSocket SslSocket = (SSLSocket) SslSFac.createSocket("localhost", portSSL);
                ois = new ObjectInputStream(SslSocket.getInputStream());
                oos = new ObjectOutputStream(SslSocket.getOutputStream());
            }
            
            //Envoie de la requête
            System.out.println("Envoie de la requête");
            String chargeUtile = NomTF.getText() + "#" + new String(PINTF.getPassword());
            RequeteAuth req = new RequeteAuth(RequeteAuth.REQUEST_AUTH,chargeUtile);
            
            oos.writeObject(req);
            oos.flush();
            
            // Lecture de la réponse      
            System.out.println("Lecture de la réponse");
            ReponseAuth rep = (ReponseAuth)ois.readObject();
            System.out.println("Reponse reçue : " + rep.getChargeUtile());
            
            
            //LReponse.setText(rep.getChargeUtile());
        } catch (IOException ex) {
            System.err.println("IOException - " + ex);
        } catch (ClassNotFoundException ex) {
            System.err.println("ClassNotFoundException - " + ex);
        }
    }//GEN-LAST:event_AuthButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnswerPanel;
    private javax.swing.JButton AuthButton;
    private javax.swing.JScrollPane DebugScrollPanel;
    private javax.swing.JTable DebugTable;
    private javax.swing.JPanel EmptyPanel;
    private javax.swing.JLabel NomBanqueLabel;
    private javax.swing.JTextField NomBanqueTF;
    private javax.swing.JLabel NomClientLabel;
    private javax.swing.JTextField NomClientTF;
    private javax.swing.JLabel NomLabel;
    private javax.swing.JTextField NomTF;
    private javax.swing.JLabel NumSerieLabel;
    private javax.swing.JTextField NumSerieTF;
    private javax.swing.JLabel PINLabel;
    private javax.swing.JPasswordField PINTF;
    private javax.swing.JPanel RequestPanel;
    // End of variables declaration//GEN-END:variables
}
